### ISSUE TITLE
Should the Alerts Banner component stay closed after it's clicked?

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system-v2#21]
One of the new components is the [Alerts Banner](https://dsws.sandbox.wvu.edu/components/essential-elements/alert-banner). 

Using [Session Storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage), we could make it so, when a user closes the alert, it will **stay closed** and not show up again until they close their current tab / window.

Would this be something desirable to add to this component? I will put together a demo shortly.

**Comment by adamglenn** [comment]
Yes, that would be cool.

**Comment by adamjohnson** [comment]
Here's [a demo](https://codepen.io/adamjohnson/pen/xxjBRLe?editors=1011). I'll submit a PR shortly.
