### ISSUE TITLE
The helper class editable region background will blend into any background that uses the bg-wvu-accent--blue-dark. 

### ISSUE THREAD

**Issue by TatsuJohnson** [wvuweb/wvu-design-system-v2#58]
The background color for the helper classes's background is the same color as the wvu-accent--blue-dark. I suggest maybe using a darker tint for this box or using some sort of outline so that people will know that the text field is there.

**Comment by adamglenn** [comment]
This is fixed. See here: https://github.com/wvuweb/wvu-design-system-v2/commit/0b461617405399f5b1716359e0229044abe789ff and here: https://github.com/wvuweb/wvu-design-system-v2/commit/34beefaf919470f222d44e698f12897ee2796b82
