### ISSUE TITLE
Dropdown menu in backpage header doesn't show children pages.

### ISSUE THREAD

**Issue by msmoirai** [wvuweb/wvu-design-system-v2#61]
I'm working on a conference page: https://www.statler.wvu.edu/events/asee-conference

I noticed that while the dropdown menu in the backpage header on the ASEE Conference page shows all of the children pages in the section, the children pages don't show all of the conference pages in the dropdown menu.

I'd like to be able to show all of that section's pages in the menu on all of the pages.

**Comment by adamglenn** [comment]
This is meant more for landing pages that don’t have a sidebar that lists child pages. However, I've made it so you can set the start depth of the menu by entering a value for the "Submenu Start Depth" property in the page properties in case you want to show sibling pages rather than children.

**Comment by adamglenn** [comment]
Here is the commit that fixes this btw: https://github.com/wvuweb/wvu-design-system-v2/commit/a3d5448264f1279ba5b2c11907d12a20bc3b77fa
