### ISSUE TITLE
Directory component's "Read More" link has an empty `href`

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/wvu-design-system-v2#78]
## Steps to reproduce the issue

  1. View the [Directory component](https://designsystem.wvu.edu/components/page-layouts/directory).
  1. Right click and inspect "Read more".

## Results

You'll notice the `href` of the link doesn't have a value. Also, there's no way to fix this in the UI (at least, in Page Properties > Custom Data).

## Expected results

The `href` attribute should automatically populate with the person's link.

## Relevant line of code:

[Line 83 of the Directory component](https://github.com/wvuweb/wvu-design-system-v2/blob/master/views/components/wvu-directory/_wvu-directory--v1.html#L83)

Probably need to change `{{ link_href }}` to `{{ item.url }}`.

**Comment by adamglenn** [comment]
This is now fixed, see here: https://github.com/wvuweb/wvu-design-system-v2/commit/9a124b31a54a4534a2c1a7a3b4c3f37c0dd382e3
